# Generated by Django 5.0.3 on 2024-04-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allparks_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.TextField(default='')),
                ('parkCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_park', to='allparks_app.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
