# Generated by Django 5.0.3 on 2024-04-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='park',
            new_name='parkCode',
        ),
    ]
